### ISSUE TITLE
Create a Start Menu

### ISSUE THREAD

**Issue by alexmdodge** [alexmdodge/gridgrind#1]
## Introduction

The start menu UI should have a start button, a high scores button, and the logo! If you're interested in spicing it up, there could be animated objects in the background moving or fading in and out
## Implementation

This project implements the Phaser framework and is written using ES5! If there are any issues with installation let me know! The buttons and the logo should be added as sprites. To create the menu the game objects should have the visibility false beforehand then switched upon starting.

**Comment by Neverbolt** [comment]
Hey there Alex,

I'd like to support you with your project, however I don't understand how the game should work. Could you put up a short explanation?

**Comment by alexmdodge** [comment]
@Neverbolt Fantastic! The game is still very early in development so new ideas are always welcome. I've updated the Readme to give a slightly more detailed explanation as to what I'm working towards. Have a read below, then check out there for some more information and eventually demo images.

## Quick Overview

You can click any of the coloured blocks and it will change them to another colour. If you click a block and it connects a **chain of colours** greater than 3, then they will disappear and your point total will increase. After a minimum number of points are reached you will move to the next level (which doesn't exist yet). 

## Strategy

The strategy comes in when you're trying to get the most points while losing the least amount of moves. I'll eventually be putting the colour order below the level so you know what will come next. If you know you want to connect the largest chain possible, and the larger the chain the more points, then knowing the order you can ensure you don't accidentally trigger another connection.

Hope this kind of makes sense! As I update the game and UI it will come together a little more, but any way to want to contribute would be greatly appreciated! Any more questions just submit them as issues!

**Comment by Neverbolt** [comment]
Perfect, the description is great.
I'll do some first work and will hopefully have a finished PR with a mock-up on Thursday.

**Comment by Neverbolt** [comment]
I'm a bit late, but I'll try to have it tomorrow
